"""Convert JSON files to deterministic, strict Luau ModuleScripts.

Usage: python tools/json2luau.py <srcdir> <outdir>
No source files are changed; unrelated output files are preserved.
"""
import argparse
import json
import math
from pathlib import Path


def quote(value):
    # Luau accepts UTF-8 directly, but JSON's \\uXXXX escape is not a Luau escape.
    result = '"'
    for char in value:
        code = ord(char)
        if char in ('"', '\\'):
            result += '\\' + char
        elif code < 32 or code == 127:
            result += f"\\{code:03d}"
        else:
            result += char
    return result + '"'


def encode(value, depth=0):
    if value is None:
        raise ValueError("JSON null cannot be represented losslessly in a Luau table")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return quote(value)
    if isinstance(value, (int, float)):
        if not math.isfinite(value):
            raise ValueError("non-finite JSON number")
        return repr(value)
    indent = "\t" * (depth + 1)
    if isinstance(value, list):
        entries = [encode(item, depth + 1) for item in value]
    elif isinstance(value, dict):
        entries = [f"[{quote(key)}] = {encode(value[key], depth + 1)}" for key in sorted(value)]
    else:
        raise TypeError(type(value))
    if not entries:
        return "{}"
    return "{\n" + "".join(indent + item + ",\n" for item in entries) + "\t" * depth + "}"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("srcdir", type=Path)
    parser.add_argument("outdir", type=Path)
    args = parser.parse_args()
    files = sorted(args.srcdir.glob("*.json"))
    if not files:
        parser.error(f"no JSON files in {args.srcdir}")
    # Validate every input before writing anything.
    modules = [(path.stem, encode(json.loads(path.read_text(encoding="utf-8-sig")))) for path in files]
    args.outdir.mkdir(parents=True, exist_ok=True)
    for name, source in modules:
        (args.outdir / f"{name}.luau").write_text(
            "--!strict\n-- Generated by tools/json2luau.py; edit the source JSON.\nreturn " + source + "\n",
            encoding="utf-8", newline="\n")
    print(f"Converted {len(modules)} JSON files into {args.outdir}")


if __name__ == "__main__":
    main()
